### PR TITLE
Migrate AppInsights Azure resources from classic to work book based

### PR DESCRIPTION
**Pull request by stishkin**
## Summary of the Pull Request

_What is this about?_

## PR Checklist
* [x] Applies to work item: #1273 
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/onefuzz) and sign the CLI.
* [x] Tests added/passed
* [ ] Requires documentation to be updated
* [x] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Info on Pull Request

_What does this include?_
Updated `azuredeploy.json` ARM template to deploy newer version of app insights

## Validation Steps Performed

_How does someone test & validate?_

Run `deploy.py` script to deploy fresh instance of OneFuzz or deploy on existing deployment to upgrade App Insights. Deploying on existing OneFuzz instance preserved app insights data.

### CODE REVIEW

**Review by bmc-msft — COMMENTED** [review]
I thought this came about because deployments in westus3 failed?  This fails to deploy in `westus3`.

I let the deployment run for an hour before stopping it.  From the script, users will see:

```
INFO:deploy:app password created
INFO:deploy:deploying arm template: azuredeploy.json
```

Then no further progress.

Looking into portal, I see the "Update hosting plan" fails *many* times  with the statement "This subscription is not allowed for the region. Please try deploying to a different region."

**Comment by bmc-msft** [comment]
Digging into the exception, it looks like there are other issues than just work book application insights.

This was deploying Microsoft.Web/serverFarms, which got the error:

```json
{
 "Code": "Forbidden",
 "Message": "This subscription is not allowed for the region. Please try deploying to a different region.",
 "Target": null,
 "Details": [
  {
   "Message": "This subscription is not allowed for the region. Please try deploying to a different region."
  },
  {
   "Code": "Forbidden"
  },
  {
   "ErrorEntity": {
    "ExtendedCode": "52032",
    "MessageTemplate": "This subscription is not allowed for the region. Please try deploying to a different region.",
    "Parameters": [],
    "Code": "Forbidden",
    "Message": "This subscription is not allowed for the region. Please try deploying to a different region."
   }
  }
 ],
 "Innererror": null
}```

**Comment by stishkin** [comment]
> Digging into the exception, it looks like there are other issues than just work book application insights.
> 
> This was deploying Microsoft.Web/serverFarms, which got the error:
> 
> ```json
> {
>  "Code": "Forbidden",
>  "Message": "This subscription is not allowed for the region. Please try deploying to a different region.",
>  "Target": null,
>  "Details": [
>   {
>    "Message": "This subscription is not allowed for the region. Please try deploying to a different region."
>   },
>   {
>    "Code": "Forbidden"
>   },
>   {
>    "ErrorEntity": {
>     "ExtendedCode": "52032",
>     "MessageTemplate": "This subscription is not allowed for the region. Please try deploying to a different region.",
>     "Parameters": [],
>     "Code": "Forbidden",
>     "Message": "This subscription is not allowed for the region. Please try deploying to a different region."
>    }
>   }
>  ],
>  "Innererror": null
> }
> ```

This error is specific to that one subscription and it is a failure to deploy ServerFarms resource to West US 3. It is not related to AppInsights Classic issue that this PR is fixing. 

I am following up on this error internally.

**Comment by stishkin** [comment]
@bmc-msft I opened #1298 to investigate failure that you reported.

**Review by bmc-msft — APPROVED** [review]

**Pull request merged**
