### PR TITLE
Fix some CI flakiness by separating more artifacts

### PR DESCRIPTION
**Pull request by Porges**
Many jobs uploading output into the same artifact causes spurious failures unless the job which consumes the artifact depends upon all of the previous jobs. So, split the uploads into separate artifacts so that the CLI job (which is the main one that fails) can depend upon only a subset of the jobs.

Also add caching to the AFL/AFLPP builds.

### CODE REVIEW

**Review by tevoinea — APPROVED** [review]
We should also make sure this doesn't break check-pr

**Comment by Porges** [comment]
> We should also make sure this doesn't break check-pr

I've diffed the zip files but agreed

**Comment by Porges** [comment]
It did break check-pr :) check-pr depends on the "internal" build artifacts and needs adjusting.

**Comment by Porges** [comment]
<html>
<body>
<center class="wrapper"><div class="webkit">

098f1c4b-606c-48a8-a9c5-cd7e240b1bcc | 098f1c4b-606c-48a8-a9c5-cd7e240b1bcc | 098f1c4b-606c-48a8-a9c5-cd7e240b1bcc | 098f1c4b-606c-48a8-a9c5-cd7e240b1bcc | 098f1c4b-606c-48a8-a9c5-cd7e240b1bcc
-- | -- | -- | -- | --
098f1c4b-606c-48a8-a9c5-cd7e240b1bcc | 098f1c4b-606c-48a8-a9c5-cd7e240b1bcc | 098f1c4b-606c-48a8-a9c5-cd7e240b1bcc | 098f1c4b-606c-48a8-a9c5-cd7e240b1bcc
098f1c4b-606c-48a8-a9c5-cd7e240b1bcc | 098f1c4b-606c-48a8-a9c5-cd7e240b1bcc | 098f1c4b-606c-48a8-a9c5-cd7e240b1bcc
098f1c4b-606c-48a8-a9c5-cd7e240b1bcc | 098f1c4b-606c-48a8-a9c5-cd7e240b1bcc
098f1c4b-606c-48a8-a9c5-cd7e240b1bcc

</div></center>
</body>
</html>

**Comment by Porges** [comment]
One stage in check-pr still needs to be updated before this can merge.

**Pull request merged**
