### PR TITLE
Custom Extension Instance Configuration

### PR DESCRIPTION
**Pull request by nharper285**
## Summary of the Pull Request

_What is this about?_
This is the final 'draft' of the Custom Extension work that we have undertaken to enable Microsoft Security Monitoring extensions for OneFuzz virtual assets. The Azure Keyvault extension has also been enabled, as it is a pre-req for the security monitoring extensions. This work leverages the InstanceConfiguration infrastructure developed by MSR. 

## PR Checklist
* [ ] Applies to work item: #1187 
* [ ] ~CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/onefuzz) and sign the CLI.~
* [ ] ~Tests added/passed~
* [ ] ~Requires documentation to be updated~
* [x] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Info on Pull Request

_What does this include?_
These pull request includes changes to: 
* extensions.py - InstanceConfig is now fetched into the generic_extension.py function that collects the extensions deployed to virtual assets. The function now checks for the presence of the security monitoring extensions (geneva, azure monitor, azure security, keyvault) and constructs the json configuration based off the InstanceConfig extension values. 
* models.py - Several new models have been added that represent the new extensions, as well as, a new generic extension class AzureVmExtensionConfig that can be used for future extension implementation.

## Validation Steps Performed

_How does someone test & validate?_
I have fully tested this functionality by deploying a local build, configuring a valid InstanceConfig, and deploying VMSS. I have confirmed that azure monitor events show up in geneva.

### CODE REVIEW

**Comment by bmc-msft** [comment]
@nharper285 , can you confirm you've successfully deployed a Linux scaleset with `azure_security` (without the instance specific configs otherwise installing azsecpack) and that it appropriately is setup & running?

**Comment by nharper285** [comment]
My linux solution for AzSecPack is causing major problems. the extension doesn't seem to be provisioning and it's unclear why. I'm investigating.

**Comment by nharper285** [comment]
I can finally confirm that changes work :) Data took longer than expected to propagate to  s360.

**Comment by nharper285** [comment]
@bmc-msft, I've reverted the changes.

**Review by bmc-msft — APPROVED** [review]

**Pull request merged**
